### PR TITLE
UHM-4683 Move Location Tag Setup out of PIH Core and into Config

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-4683

@mogoodrich if you wouldn't mind taking a look to make sure this is sort of what you were envisioning

### CODE REVIEW

**Comment by brandones** [comment]
Started the Capitan location locally and verified the location tags

**Comment by mogoodrich** [comment]
@brandones yeah, that looks good @brandones , with a few caveats regarding testing:

* Just a reminder, you will need to remove the "Mexico" part of LocationTagSetup in the PIH Core module (or just remove the entire legacy setup) to confirm that it's the config, not the LocationTagSetup, that is doing the setup

* It's annoying, but we should use the SDK to fire up each country from scratch to test that workflow as well

**Comment by brandones** [comment]
Sweet. I feel quite confident that if it does a country from scratch, that it will do any country from scratch—any reason to be skeptical of that?

**Comment by mogoodrich** [comment]
@brandones it's for more double-checking the actual migration work and making sure you didn't forget anything, more than testing the code. iirc, the way the code works is it only clears out a and resets a location tag if it's specified in th econfig. So, I believe, for example, if you forget to add the "mch" tag to a country config and then test on an existing implementation, it will look fine since it was previously set up via code, but if you start from scratch it will be missing.  You could just manually clean out all the tags in the DB instead.

**Comment by brandones** [comment]
Yeah, actually, doing `delete from location_tag_map` and restarting the server seems to do the trick :+1:

**Pull request merged**
