### PR TITLE
MEX-513 Add minimal required ETL job to PETL to test process and configuration

### PR DESCRIPTION
**Pull request by jmbabazi**
https://pihemr.atlassian.net/browse/MEX-513

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
LGTM @jmbabazi !

**Review by brandones — APPROVED** [review]
Awesome, thanks @jmbabazi !

**Comment by mseaton** [comment]
Actually, only issue here @jmbabazi and @brandones - didn't @brandones set up a new repository at PIH/ces-etl.git where he intended all of this to go?

**Comment by brandones** [comment]
Yeah I'm not very opinionated about how it should be done, but I think that would make sense. The repo is here: https://github.com/PIH/ces-etl/ . We just need to be able to deploy it, along with the azbackup unpacking stuff, to a single specific server which is not necessarily a server that is running OpenMRS.

**Comment by mseaton** [comment]
I think either way works - we are deploying all of the ZL PETL stuff currently in the openmrs-config-zl package onto server(s) that don't necessarily run OpenMRS.  And in Malawi, we created an apzu-etl project similar to the ces-etl you created, and added build configuration so that it is deployed as a zip to maven on each commit.

**Pull request merged**
