### PR TITLE
MEX-357 Should be able to mark patient as dead

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/MEX-357

screenshot--2020-12-11--131212
Screenshot from 2020-12-11 10-11-33

### CODE REVIEW

**Comment by mogoodrich** [comment]
LGTM!

**Comment by brandones** [comment]
Thanks @mogoodrich . Waiting for Jose Garcia to create a GitHub account to add him to review.

**Comment by brandones** [comment]
Ping @Joseph-Developer

**Comment by brandones** [comment]
@Joseph-Developer

**Review by Joseph-Developer — APPROVED** [review]

**Pull request merged**
